name: CI

on: [push]

jobs:
  build:
    run-on: ubuntu-latest
    steps:
      -users: actions/checkout@v2
      -name: Use node 18.11
       uses: actions/setup-node@v2
       with:
         node-version: 18.16.0
      -name: Install dependencies
       run: npm ci
      - name: Run tests
        run: npm run test:unit

